---
title: "climate_change"
author: "Naina Tejani"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readtext)
library(janitor)
library(readxl)
library(dplyr)
theme_set(theme_bw())
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rworldmap)
library(ggthemes)
library(gganimate)
library(transformr)
library(tweenr)
library(spData)
library(tibble)
library(forcats)
library(httr)
library(broom)
library(gt)

options(mc.cores=parallel::detectCores())
```
```{r fetching_data, cache=TRUE}
# Get the data directory from readtext
# the following code is commented since I only needed to run it once.
#DATA_DIR <- system.file("extdata/", package = "readtext")

#fn <- "http://climate.geog.udel.edu/~climate/html_pages/Global2014/air_temp_2014.tar.gz"
#download.file(fn,destfile="air_temp_2014.tar.gz")
#untar("air_temp_2014.tar.gz")  ## check contents

```

```{r cleaning_data, include=FALSE}
forest <- read_excel("raw-data/forestArea.xls", skip = 2) %>%
  clean_names() %>%
  filter(! is.na (country_name))
co2 <- read_excel("raw-data/co2.xls", skip = 2) %>%
  clean_names() %>%
  filter(! is.na (country_name))
oil <- read_excel("raw-data/oilConsumption.xls", skip = 2) %>%
  clean_names() %>%
  filter(! is.na (country_name))
```
```{r wrangling_data,include=FALSE}

co2_pivoted <- co2 %>%
  
  # I learned that you can remove specific prefix from the name of the column by
  # using names_prefix
  
  pivot_longer(starts_with("x"), names_to = "year", names_prefix = "x", values_to = "emissions_per_capita") %>%
  
  select(country_name, country_code, indicator_name, `year`, `emissions_per_capita`) %>%
  filter(!is.na(emissions_per_capita)) %>% 
  
  # I arrange by country_name because I want to replicate the order of the rows
  # shown in the exam document file.
  
  arrange(country_name) %>%
  
  # the reason I convert year to double type is because in the paris table, the
  # year is type double and in order to join the tables by year, the year needs
  # to be of the same type.
  
  mutate(year = as.double(year)) %>% 
  filter(!is.na(emissions_per_capita))

oil_pivoted <- oil %>%
  
  # I learned that you can remove specific prefix from the name of the column by
  # using names_prefix
  
  pivot_longer(starts_with("x"), names_to = "year", names_prefix = "x", values_to = "energy_use") %>%
  
  select(country_name, country_code, indicator_name, `year`, `energy_use`) %>%
  
  # I arrange by country_name because I want to replicate the order of the rows
  # shown in the exam document file.
  
  arrange(country_name) %>%
  
  
  # the reason I convert year to double type is because in the paris table, the
  # year is type double and in order to join the tables by year, the year needs
  # to be of the same type.
  
  mutate(year = as.double(year)) %>% 
  filter(!is.na(energy_use)) 

forest_pivoted <- forest %>%
  
  # I learned that you can remove specific prefix from the name of the column by
  # using names_prefix
  
  pivot_longer(starts_with("x"), names_to = "year", names_prefix = "x", values_to = "forest_area") %>%
  
  select(country_name, country_code, indicator_name, `year`, `forest_area`) %>%
  
  # I arrange by country_name because I want to replicate the order of the rows
  # shown in the exam document file.
  
  arrange(country_name) %>%
  
  
  # the reason I convert year to double type is because in the paris table, the
  # year is type double and in order to join the tables by year, the year needs
  # to be of the same type.
  
  mutate(year = as.double(year)) %>% 
  filter(!is.na(forest_area)) 

```


```{r create_dataframe_for_all_temperatures, include=FALSE}

# Creating my data frame called df with values of temperature for all 114 years,
# for each longitude and latitude.

df <- data.frame(year=integer(),
long=double(),
lat=double(),
change_in_temp=double()) 


# The following code inserts all temperature values into my initialized
# dataframe called df.

# This was a fun function to write about. I learnt how to use rbind. I also
# learnt how to read txt files which do not necessarily end with a .txt or
# really any conventional extension. Moreover, I realized that sometimes various
# packages may have the same functions and that may interfere with the workings
# of the functions, which is why below I had to specify dplyr for the filter
# method.

# The reference table is the data frame which I am comparing all other temperatures to. It depends on the previous year calculated.
ref_tbl <- read.table('raw-data/temp_data/air_temp.1900')
my_seq <- seq(from = 1910, to = 2014, by = 1)
for (i in my_seq){
  tbl <- read.table(paste('raw-data/temp_data/air_temp.', i ,sep ='')) %>% 
    rename("long" = V1, "lat" = V2) %>% 
    mutate(mean_yearly_temp = (V3+V4+V5+V6+V7+V8+V9+V10+V11+V12+V13+V14)
         /12, 
         year = i) %>% 
    dplyr::select(long, lat, mean_yearly_temp, year)
  
  change_in_temp <- ref_tbl %>% 
    inner_join(tbl, by = c("long", "lat")) %>% 
    mutate(change_in_temp = mean_yearly_temp.x - mean_yearly_temp.y,
           year = year.y) %>% 
    select(long, lat, change_in_temp, year)
   
  ref_tbl <- tbl
  df <- rbind(df, change_in_temp)
}

# I actually did not end up using this df table since it was essentially to
# create animations which did not work out.

```

```{r year_temperatures, include=FALSE}
# This essentially computes the temperatures at each longtiude and longitude for
# a given year. As can be seen, it takes the average of 12 monthly temperature
# averages.

year_temperatures <- function(year){
  read.table(paste('raw-data/temp_data/air_temp.', year, sep = '')) %>%
   rename("long" = V1, "lat" = V2) %>%
   mutate(mean_yearly_temp = (V3+V4+V5+V6+V7+V8+V9+V10+V11+V12+V13+V14)
          /12) %>%
   dplyr::select(long, lat, mean_yearly_temp)
}
year_temperatures(1900)

```
```{r change_of_temp_between_2_years, include=FALSE}
# This function computes the change in temperatures between two years.

change <- function(year, ref_year) { 
  read.table(paste('raw-data/temp_data/air_temp.', year, sep='')) %>%
   rename("long" = V1, "lat" = V2) %>%
   mutate(mean_yearly_temp = (V3+V4+V5+V6+V7+V8+V9+V10+V11+V12+V13+V14)
          /12) %>%
   dplyr::select(long, lat, mean_yearly_temp) %>% 
   inner_join(year_temperatures(ref_year), by = c("long", "lat")) %>% 
   mutate(change_in_temp = ifelse(mean_yearly_temp.x - mean_yearly_temp.y > 5.0, 5.0,
                                  ifelse(mean_yearly_temp.x - mean_yearly_temp.y < -5.0,
                                         -5.0, mean_yearly_temp.x - mean_yearly_temp.y))
          ) 
}

```
```{r plot_change_between_two_years, include=FALSE}

# I had to do significant trial and error with the maps. My most important
# decision was whether to compare each decade with 1900, or compare each decade
# with the once preceding it. I enetually decided to compare each decade with
# 1900 because my primary goal is to show an incremental change in temperature.

plot = function (year){
  shp <- read_sf("Lat_Long/Lat_Long.shp")
  data <- change(year, 1900)
  locate_sf <-  st_as_sf(data, coords = c("long", "lat"), crs = 4326)
  
  ggplot(data = shp) +
    geom_sf() +
    geom_sf(data = locate_sf, aes(color = change_in_temp)) +
    theme_map() +
    labs(color = "Change in Temperature", title = paste("Year ", year, "Compared to Year 1900")) +
    scale_color_gradient(low = "yellow", high = "red", limits = c(-5,5))
}
# I used the above plot function to create all my maps which we see in the heat visualizations. To create a plot and save it, i use the following code

plot_year = plot(2014)
ggsave(plot_year, file = paste("climate_change_shiny/maps1/map2014.jpeg"))


```

```{r attempt_at_animations, include=FALSE}
# I tried to run the following code for animations. However, the code was too
# slow. Even after leaving overnight for 10 hours did not produce the animation.
# I would love to figure this out.

shp <- read_sf("Lat_Long/Lat_Long.shp")
locate_sf <-  st_as_sf(df, coords = c("long", "lat"), crs = 4326) %>%
  select(change_in_temp, year, geometry)
ggplot(ind_shp) +
  geom_sf() +
  geom_sf(data = locate_sf, aes(color = change_in_temp)) +
  theme_map() +
  transition_time(year) +
  labs(color = "temperature", subtitle = "Year {frame_time}", title = "Heat Maps")+
  scale_color_gradient(low = "yellow", high = "red")

```

```{r temeprature_change_with_time, include=FALSE}
sequence = seq(from=1900, to=2014,by = 1)

# I create a list of all mean yearly temperatures in the for loop below.

temps <- c()
for (year in sequence){
   yearly_temp<-read.table(paste('raw-data/temp_data/air_temp.', year, sep='')) %>%
     rename("long" = V1, "lat" = V2) %>%
     mutate(mean_yearly_temp = (V3+V4+V5+V6+V7+V8+V9+V10+V11+V12+V13+V14) /12) %>%
     select(long, lat, mean_yearly_temp) %>% 
     summarise(avg = mean(mean_yearly_temp)) %>%
     pull(avg)
   temps <- append(temps,yearly_temp)
}     
    
# I create a new tibble to show the progression of temperature change with time.
years_and_temp <- tibble(year = 1900:2014,
                         temp = temps)

```
```{r creating_temp_with_time_plot, include=FALSE}
climate_change_plot <- years_and_temp %>%
  ggplot(aes(year,temp)) +
  geom_point(color = "red") +
  geom_smooth(method = 'lm', se=FALSE) +
  theme_classic() +
  labs("Climate Change Over The Past Century", x = "Year", y = "Annual Mean Temperature")
write_rds(climate_change_plot, "final_project_shiny/climate_change_plt.rds")
climate_change_plot
```
```{r regression_and_plots_for_co2_and_forest_area, include=FALSE}
# I first create the suitable table linknig co2 and temperature. I make sure to
# only account for years where I have values for both.

# I log the co2 emissions since the data is concentrated on the right and hence
# a straight line does not do justice to the rekation.

co2_temp <- co2_pivoted %>% 
  group_by(year) %>%
  summarise(emissions = log(mean(emissions_per_capita)))%>%
  mutate(temps = temps[61:115]) 

# I then create a plot showing how co2 emissions are correlated with high temperatures.

co2_temp_plot <- co2_temp %>%
  ggplot(aes(emissions, temps)) +
  geom_point() +
  theme_classic() +
  geom_smooth(method = lm, se=FALSE) +
  labs(title = "Effect of CO2 emissions on Global Temperatures", x = "CO2 Emissions(metrics tons per capita)", y = "Mean Annual Temperatures", subtitle = "Emissions has been logged")
co2_temp_plot

# I then run a regression to explore the relationship further.
regression_co2 <- co2_temp %>% 
  lm(temps ~ emissions, data = .) %>% 
  tidy(conf.int=TRUE) %>% 
  select(term, estimate,conf.low, conf.high ) %>% 
  mutate(estimate = round(estimate, 3), conf.low = round(conf.low, 2),conf.high = round(conf.high, 2)) %>% 
  rename("Term" = "term", "Estimate" = "estimate","Lower Bound" = "conf.low", "Upper Bound" = "conf.high") %>% 

regression_co2
write_rds(regression_co2, "climate_change/regression_co2.rds")

# I repeat the same steps for forest data.
forest_area_temp <- forest_pivoted %>% 
  group_by(year) %>% 
  summarise(forest_area = log(mean(forest_area))) %>%
  filter(year <= 2014) %>% 
  mutate(temps = temps[91:115])
forest_area_temp

forest_temp_plot <- forest_area_temp %>%
  ggplot(aes(forest_area, temps)) +
  geom_point() +
  theme_classic() +
  geom_smooth(method = lm, se=FALSE) +
  labs(title = "Effect of Forest Area on Global Temperatures", x = "Forest Area(square km)", y = "Mean Annual Temperatures", subtitle = "The data ranges from year 1990 to 2016")
forest_temp_plot
write_rds(forest_temp_plot, "climate_change/forest_temp_plot.rds")

regression_forest_area <- forest_area_temp %>% 
  lm(temps ~ forest_area, data = .) %>% 
  tidy(conf.int=TRUE) %>% 
  select(term, estimate,conf.low, conf.high ) %>% 
  mutate(estimate = round(estimate, 3), conf.low = round(conf.low, 2),conf.high = round(conf.high, 2)) %>% 
  rename("Term" = "term", "Estimate" = "estimate","Lower Bound" = "conf.low", "Upper Bound" = "conf.high")

forest_area_temp %>% 
  summarise(coef = cor(forest_area, temps)) %>% 
  pull(coef)
regression_forest_area

  
```



```{r comparing_co2_emissions_with_energy_consumptions,include=FALSE}
joined_tbl <- co2_pivoted %>% 
  inner_join(oil_pivoted, by = c("year", "country_code", "country_name")) %>% 
  filter(! is.na(energy_use) & ! is.na(emissions_per_capita))

write_rds(joined_tbl, 'final_project_shiny/C02_Emissions_And_OIL.rds')
joined_tbl1 <- co2_pivoted %>% 
  inner_join(forest_pivoted, by = c("year", "country_code", "country_name")) %>% 
  filter(! is.na(forest_area) & ! is.na(emissions_per_capita))
```


```{r testing_plots}

# This section is for me anaylzing the relationships and testing correlations.
country_names

for (country in country_names){
      plt <- joined_tbl %>%
               filter(country_name == input$country) %>% 
               ggplot(aes(x = energy_use, 
                          y = emissions_per_capita)) +
               geom_point() 
               theme_classic() +
               labs(title = paste("Change in CO2 Emissions with Rising Oil Consumption  For ", country, sep = ''),
                            x = "Energy Use(kg of oil equivalent per capita)",
                            y = "Emissions of CO2(metric tons per capita)"
                       )
      write_rds(plt, paste('final_project_shiny/plots/plot',country, ".rds",sep =''))

}
plot1 <- joined_tbl %>% 
  filter(country_name == "Albania") %>% 
  ggplot(aes(x = energy_use, y = emissions_per_capita, color = country_code)) +
geom_point() +
  theme_classic() + 
  labs(title = "Comparison of CO2 Emissions between United States and United Arab Emirates with time", x = "Energy Use(kg of oil equivalent per capita)", y = "Emissions of CO2(metric tons per capita)")

plot1


plot2 <- joined_tbl %>%
  mutate(energy_use_log = log(energy_use)) %>%
  ggplot(aes(x = energy_use_log, y = log(emissions_per_capita))) +
geom_jitter(alpha = 0.2) +
  theme_classic() +
  geom_smooth(method = "lm", se = FALSE)
plot2

country_names <- joined_tbl %>%
  pull(country_name) %>%
  unique()
country_names 

write_rds(country_names, "final_project_shiny/country_names.rds")

# plot3 <- joined_tbl1 %>% 
#   ggplot(aes(x = log(forest_area), y = (emissions_per_capita))) +
#   theme_classic() +
#   geom_histogram(binwidth=10 )
# ?geom_histogram
# plot3

```

